### PR TITLE
Add Spanish locales & models

### PR DESCRIPTION
**Pull request by alexbcberio**
I have added a locale and speech model to support spanish, I have tested them but some of them do throw an error. I am assuming that the errors come from the code itself as the data is being sent to the skill.

Also the skill seems to not take correctly some translations, such as the one on the line 59 "Sorry, something went wrong. Please try again."

Here is a trace of one of the errors
```txt
Traceback (most recent call last):
jellyfin_alexa_skill  |   File "/opt/venv/lib/python3.10/site-packages/ask_sdk_runtime/dispatch.py", line 118, in dispatch
jellyfin_alexa_skill  |     output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
jellyfin_alexa_skill  |   File "/opt/venv/lib/python3.10/site-packages/ask_sdk_runtime/dispatch.py", line 182, in __dispatch_request
jellyfin_alexa_skill  |     output = supported_handler_adapter.execute(
jellyfin_alexa_skill  |   File "/opt/venv/lib/python3.10/site-packages/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
jellyfin_alexa_skill  |     return handler.handle(handler_input)
jellyfin_alexa_skill  |   File "/opt/venv/lib/python3.10/site-packages/jellyfin_alexa_skill-0.3.2.dev4-py3.10.egg/jellyfin_alexa_skill/alexa/handler/base.py", line 27, in handle
jellyfin_alexa_skill  |     return self.handle_func(user=user, handler_input=handler_input, *args, **kwargs)
jellyfin_alexa_skill  |   File "/opt/venv/lib/python3.10/site-packages/jellyfin_alexa_skill-0.3.2.dev4-py3.10.egg/jellyfin_alexa_skill/alexa/handler/base.py", line 39, in wrapper
jellyfin_alexa_skill  |     return func(self, handler_input=handler_input, translation=translation, *args, **kwargs)
jellyfin_alexa_skill  |   File "/opt/venv/lib/python3.10/site-packages/jellyfin_alexa_skill-0.3.2.dev4-py3.10.egg/jellyfin_alexa_skill/alexa/handler/control.py", line 375, in handle_func
jellyfin_alexa_skill  |     .resolutions.resolutions_per_authority[0].values[0].value.id
jellyfin_alexa_skill  | AttributeError: 'NoneType' object has no attribute 'resolutions_per_authority'
```

> **Note**: I am not very confident on Python, so I might have done something wrong. Be sure to check the changes.

### CODE REVIEW

**Comment by rikman122** [comment]
Hi! Looks like locales file isn't correct. Take a look at the italian one, it looks like you must leave "msgid" as it is in english and asign the translation to the "msgstr" field. I was about to do it for Spain too but if you want just add that change and it should work

**Comment by alexbcberio** [comment]
Oh, that makes lot of sense. I will fix and push the changes

Thanks!

**Comment by rikman122** [comment]
Did you managed to get it working? I'm getting:

INFO:Cloud skill version:
         Current skill version: 0.3.1
INFO:[es-ES] invocation name changed to "None"
INFO:Updating skill interaction model...
INFO:Skill interaction model for locale es-ES is updated
INFO:All skill interaction models updated
INFO:Updating skill manifest...
Traceback (most recent call last):
  File "/usr/local/bin/jellyfin_alexa_skill", line 11, in <module>
    load_entry_point('jellyfin-alexa-skill==0.3.1', 'console_scripts', 'jellyfin_alexa_skill')()
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_alexa_skill-0.3.1-py3.7.egg/jellyfin_alexa_skill/main.py", line 382, in main
    stage)
  File "/usr/local/lib/python3.7/dist-packages/jellyfin_alexa_skill-0.3.1-py3.7.egg/jellyfin_alexa_skill/main.py", line 235, in update_skill_manifest
    update_skill_request=new_manifest)
  File "/usr/local/lib/python3.7/dist-packages/ask_smapi_model/services/skill_management/skill_management_service_client.py", line 13540, in update_skill_manifest_v1
    response_type=None)
  File "/usr/local/lib/python3.7/dist-packages/ask_sdk_model_runtime/base_service_client.py", line 146, in invoke
    body=exception_body)
ask_sdk_model_runtime.exceptions.ServiceException: Server cannot process the request due to a client error.

**Comment by alexbcberio** [comment]
Yestarday I was getting errors updating the spanish models and I ended up pasting the json manually on the console.
I also have updated the version (not committed) to force updating the models/strings.

**Comment by rikman122** [comment]
Hi,

I can confirm this is working.

Thak you

**Comment by infinityofspace** [comment]
Thank you for your translation PR.

From my side everything looks fine and runs without problems.

Regarding the errors when updating the models or the manifest, it is very likely that the models were not updated correctly or only partially in the cloud.
Therefore, during development and translation, the `force_reset_skill attribute` in the [config](https://github.com/infinityofspace/jellyfin_alexa_skill/blob/9434a62fcbc3877f46d1b37688059d43c06ba668/skill.conf#L17) should be set to `true`.
This ensures that all previous customization whether automatic or in the Alexa Web Console, are overwritten with the current local skill models and manifest. This point is missing in the instructions for the translations, I have added it now.

---

As a note, if you would like to help further with the translation: Translations using PR will soon be replaced by Crowdin. This has the advantage that also technically less experienced users can contribute translations and also the future translations can be integrated easier and faster. Therefore, no new translation PR will be accepted after this. If you would like to continue helping with the translation, feel free to check the repo from time to time in the next weeks. The open call for translations will be announced on the repo page.

**Pull request merged**
