### PR TITLE
support for video playback

### PR DESCRIPTION
**Pull request by Yahoo-Mike**
This relates to issue #2 (add support for video playback).

This first commit plays videos, but it's not ready to merge yet.  Still to be done:

1. integrate the AMAZON intents (resume, repeat, etc), which are currently not working.
2. stress test the code a little more
3. add a test to ensure that the Alexa device has display capabilities.  For example, Amazon Echo and Sonos speakers do not have video displays - so I guess Alexa will just have to remind the user.

### CODE REVIEW

**Comment by Yahoo-Mike** [comment]
Latest commits check if device supports video before launching VideoApp. 

### Notes on VideoApp and Intents
All the control intents work as expected, except "repeat" (see below).

According to the [VideoApp reference](https://developer.amazon.com/en-US/docs/alexa/custom-skills/videoapp-interface-reference.html):

-  Pause/Resume works (handled by VideoApp)
-  Stop/close works (handled by VideoApp)
-  Restart works (handled by VideoApp)
-  CancelIntent is not supported  (Alexa ignores the request and doesn't pass the CancelIntent on to the skill for processing)
 
By the way, according to the same reference, you can only launch one video at a time.  So you can't queue a "next video".

### ISSUE:  "Alexa Repeat" does nothing
**Expected result**: repeat the last video played
**Comments**:
- AMAZON.RepeatIntent is currently not handled by jellyfin_alexa_skill
- instead the custom RepeatSingleOnIntent ("Alexa Repeat that/the video") just sets the "loop_single" flag.
- the "loop_single" flag is used by the NearlyFinishedEvent handler for AudioPlayer
- VideoApp does not send a NearlyFinished event message

So the code has to treat audio and video differently.  For videos, it just needs to re-launch the video.

To acheive this we could add a column to the Playback db table that records the type of media/player ("audio"/"video") used to play the media.  Then when a RepeatIntent/RepeatSingleOnIntent arrives, we can check the media type and treat audio and video differently.  The only other way to do this is to query jellyfin again (everytime an Intent arrives) using the "Id" to work out if it's an audio or video stream - that seems a bad solution.
 
I can do this, but I'm happy to hear other suggestions.

**Comment by infinityofspace** [comment]
Thank you for your PR. The current commits looks good.

**Regarding the RepeatIntent issue:**
This intent as well as some others like some button media controls are currently not handled by the skill. Especially the button media control would probably be useful for video playback (also for audio playback with UI devices). The reason for the additional intent for the repeat handling, was the adjustment of the intent statements, because this was not possible with the standard intent. Especially important here is the point with switching on and off the repeats. With the default intent, switching to on or off repeats was somewhat ambiguous. Maybe the standard RepeatIntent can additionally be used as switcher of the loop_single flag. The peculiarity with the NearlyFinshed event is of course not so good, since for iteration in the current playback queue we need to know if the video has been played. Unfortunately I don't have a solution to still use the playback queue at the moment. The only possible solution would be implementable with the request proxy first. However, this requires some more major internal changes.

**Regarding the media type:**
Your suggestion with the media type in the Playback DB column would make sense. For example, a tuple with `(id, media_type)` would be reasonable. In this step one could also come up with the idea to store additional data, such as the title or the artists in the DB. However, this would not be very helpful since in this case we have a data duplication in two different places (in the Skill DB and on the Jellyfin server). In this case it would be problematic because the data on the Jellyfin server could be changed and we would have to make sure that the data in the Skill DB is always up to date. However, saving only the media type together with the id would be very helpful, as it should not change (if I understood Jellyfin's ID assignment correctly). With this storage we can directly skip such element with a hint when resuming a playback or playing a playlist with mixed media (audio and video).

**Comment by Yahoo-Mike** [comment]
I understand.  It's a shame that Amazon chose different interfaces for Alexa's audio and video players.

Maybe we leave the RepeatIntent for a future enhancement.

So this PR is ready for the next release.

**Comment by infinityofspace** [comment]
All right, I will merge the branch then. And add the compiled mo files.

Thanks for your help to improve the skill.

**Pull request merged**
